
name: Sync Changes to All Repositories

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v3
        with:
          repository: engineercode36/broken-barrier-progress
          # Use GitHub's built-in token for authentication
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set Up Git
        run: |
          git config user.name "GitHub Action Bot"
          git config user.email "actions@github.com"

      - name: Sync with Other Repositories
        env:
          # Use a repository secret instead of hardcoding the token
          GH_PAT: ${{ secrets.SYNC_PAT }}
        run: |
          # List of repositories to sync
          REPOS=("https://github.com/canlife4ever/note-haven-syntax-21.git")

          # Use the secret token from repository settings
          git config --global credential.helper store
          echo "https://${GH_PAT}:@github.com" > ~/.git-credentials

          # Check out the repository
          if [ ! -d ".git" ]; then
            echo "Repository not found. Exiting."
            exit 1
          fi

          # Loop through each repository and push changes
          for repo in "${REPOS[@]}"; do
            echo "Syncing with $repo"

            # Add remote only if not already added
            if ! git remote get-url target 2>/dev/null; then
              git remote add target "$repo"
            fi

            # Push changes to the target repository
            if git push --mirror target; then
              echo "Successfully pushed to $repo"
            else
              echo "Failed to push to $repo"
            fi

            # Remove the remote after sync
            git remote remove target
          done

          # Remove the git-credentials after the sync is done
          rm -f ~/.git-credentials

