
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables with fallbacks
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Log the initialization with key format check
console.log("Initializing Supabase client in integrations with URL:", SUPABASE_URL);
console.log("API Key format check (integration client):", SUPABASE_ANON_KEY ? `Key length: ${SUPABASE_ANON_KEY.length}` : "Missing key");

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Always use the same key across the application
export const supabase = createClient<Database>(
  SUPABASE_URL || "https://xyzcompany.supabase.co",
  SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5emNvbXBhbnkiLCJyb2xlIjoiYW5vbiIsImlhdCI6MTYwMDAwMDAwMCwiZXhwIjoyMDAwMDAwMDAwfQ.Rl41HWI8A4tGS4WjOVgD6jNg42xk_XiKQbDrEcBtAhA"
);
